name: ci-push

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/cuautodrone/cuad-ros:main

jobs:
  docker-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Get Git commit timestamps
        run: echo "TIMESTAMP=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Get ROS Apt Source Version
        run: echo "ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}')" >> $GITHUB_ENV

      - name: Validate Build Configuration
        uses: docker/bake-action@v6
        with:
          targets: validate-build
          set: "default.args.ROS_APT_SOURCE_VERSION=${{ env.ROS_APT_SOURCE_VERSION }}"
        env:
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}

      - name: Build
        uses: docker/bake-action@v6
        with:
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file }}
          targets: default
          set: |
            default.args.ROS_APT_SOURCE_VERSION=${{ env.ROS_APT_SOURCE_VERSION }}
            default.tags=${{ env.IMAGE_NAME }}
          push: true
          provenance: true
          sbom: true
        env:
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}