name: ci-push

on:
    pull_request_target:
        types:
            - labeled

env:
    IMAGE_NAME: ghcr.io/cuautodrone/cuad-ros

jobs:
    docker:
        if: contains(github.event.pull_request.labels.*.name, 'pr-pull')
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
          security-events: write
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set Up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set Up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Push Image to GitHub Container Registry
              run: |
                docker buildx imagetools create \
                --tag ghcr.io/cuautodrone/cuad-ros:latest \
                ghcr.io/cuautodrone/cuad-ros:test

            - name: Scout
              uses: docker/scout-action@v1
              with:
                command: quickview,cves,recommendations
                image: ghcr.io/cuautodrone/cuad-ros:latest
                platform: all
                sarif-file: sarif.output.json
                registry-user: ${{ github.repository_owner }}
                registry-password: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload SARIF Results
              id: upload-sarif
              uses: github/codeql-action/upload-sarif@v2
              with:
                sarif_file: sarif.output.json

            - name: Merge PR
              run: gh pr merge